kind = "web"
previewPath = "/"
title = "Tirthon Tech"
version = "1.0.0"
id = "artifacts/tirthon-tech"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23014

[services.development]
run = "pnpm --filter @workspace/tirthon-tech run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tirthon-tech", "run", "build" ]
publicDir = "artifacts/tirthon-tech/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23014"
BASE_PATH = "/"
